名称：自动同步
上：推
职位：
  mirror_to_gitee：
    运行：ubuntu-latest
    步骤：
      -名称：“结帐”
        用途：actions / checkout @ v1
      -名称：“镜报gitee ”
        用途：pixta-dev / repository-mirroring-action @ v1
        与：
          target_repo_url：
            $ {{secrets.GITEE_URL}}
          ssh_private_key：
            $ {{secrets.GITEE_KEY}}

  mirror_to_gitlab：
    运行：ubuntu-latest
    步骤：
      -名称：“结帐”
        用途：actions / checkout @ v1
      -名称：'镜像到gitlab '
        用途：pixta-dev / repository-mirroring-action @ v1
        与：
          target_repo_url：
            $ {{secrets.GITLAB_URL}}
          ssh_private_key：
            $ {{secrets.GITLAB_KEY}}
